// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /home/zyh/GitHub/gocompile/golang-go/src/internal/race/norace.go

//line /home/zyh/GitHub/gocompile/golang-go/src/internal/race/norace.go:1
// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build !race
// +build !race

package lscq

import (
	"unsafe"
)

const raceEnabled = false

func raceDisable() {
}

func raceEnable() {
}

func raceReleaseMerge(addr unsafe.Pointer) {
}

func raceAcquire(addr unsafe.Pointer) {
}
